# Generated by Django 5.1.6 on 2025-03-02 21:48

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Model Name')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rated_output_power', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_output_current', models.CharField(blank=True, max_length=255, null=True)),
                ('input_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('input_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('output_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('output_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('vfd_series', models.CharField(blank=True, max_length=20, null=True)),
                ('supply_voltage_ac', models.CharField(blank=True, max_length=10, null=True)),
                ('rated_power_hp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('application', models.CharField(blank=True, max_length=20, null=True)),
                ('plc_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Input (PLC)')),
                ('plc_output', models.CharField(blank=True, max_length=255, null=True, verbose_name='Output (PLC)')),
                ('supply_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('output_type', models.CharField(blank=True, max_length=255, null=True)),
                ('display_device', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('display_size', models.CharField(blank=True, max_length=255, null=True)),
                ('display_color', models.CharField(blank=True, max_length=255, null=True)),
                ('built_in_interface', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_output', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_torque', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_torque', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('power_supply_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('power_supply_input', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('rated_current', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_current', models.CharField(blank=True, max_length=255, null=True)),
                ('control_method', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamic_brake', models.CharField(blank=True, max_length=255, null=True)),
                ('encoder_type', models.CharField(blank=True, max_length=255, null=True)),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('encoder_resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('servo_motor', models.CharField(blank=True, max_length=255, null=True)),
                ('servo_amplifier', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='(W x H x D in mm)', max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('compatible_software_package', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category')),
                ('related_products', models.ManyToManyField(blank=True, related_name='linked_products', to='eshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Canceled'), ('D', 'Delivered')], default='P', max_length=1)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='eshop.quotation')),
            ],
        ),
    ]
